In [1]:
import numpy as np

In [2]:
vector = np.array([1,7,3,5,6])
matriz = np.diag(vector)
matriz#matriz cuadrada

array([[1, 0, 0, 0, 0],
       [0, 7, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

In [3]:
matriz[:4,:3]

array([[1, 0, 0],
       [0, 7, 0],
       [0, 0, 3],
       [0, 0, 0]])

In [4]:
matriz[:3,:4]

array([[1, 0, 0, 0],
       [0, 7, 0, 0],
       [0, 0, 3, 0]])

In [6]:
vector = np.array([2,4,5,2,5])
vector = np.expand_dims(vector,axis=1)
vector

array([[2],
       [4],
       [5],
       [2],
       [5]])

In [7]:
matriz.dot(vector)

array([[ 2],
       [28],
       [15],
       [10],
       [30]])